[build-system]
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
addopts = "-q --cov=app --cov-branch --cov-report=term-missing --cov-fail-under=100"
testpaths = ["tests"]
pythonpath = ["."]
